#!/usr/bin/python

import sys

for x in xrange(5):
    sys.stdout.write('77 ' * 5)
    sys.stdout.write('FF ' * 5)
    sys.stdout.write('\n')
for x in xrange(5):
    sys.stdout.write('FF ' * 5)
    sys.stdout.write('77 ' * 5)
    sys.stdout.write('\n')
